# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            †∆¥Ø
tagline:          'Hola'
description:      'A website by <a href="https://twitter.com/tayoxlife" target="_blank">@tayoxlife</a>.'
url:              http://tayo.co
baseurl:          /

author:
  name:           'Nathan Rothenberger'
  url:            https://twitter.com/tayoxlife

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/tayox/tales

sass:
  sass_dir: assets/css
  # style: :nested

# Development
port:							4020