
# Navigation
nav:
- {name: Portfolio, url: 'https://www.behance.net/nroth10'}
# - {name: Blog, url: '/blog'}
- {name: Hire Me, url: '/job'}
- {name: Contact, url: 'mailto:nroth10@gmail.com'}
# - {name: Projects, url: '/projects'}

#-------------------------------
# Social

social:
- {icon: 'twitter', 	link: 'http://twitter.com/tayoxlife'}
- {icon: 'instagram', link: 'https://instagram.com/tayox'}
# - {icon: 'dribbble', 	link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', 	link: 'https://www.behance.net/nroth10'}
# - {icon: 'youtube', 	link: 'https://www.youtube.com/DevTipsForDesigners'}
# - {icon: 'linkedin', 	link: 'http://www.linkedin.com/in/travisneilson/'}
# - {icon: 'facebook', 	link: 'http://www.facebook.com/$username/'}
# - {icon: 'tumblr', 		link: 'http://tayox.tumblr.com'}
# - {icon: 'pinterest', link: 'http://www.pinterest.com/$username/'}	


contact:
- {type: phone, data: '503.810.3903', 		 icon: phone, 	 url: "#" }
- {type: email, data: 'nroth10@gmail.com', icon: envelope, url: "mailto:nroth10@gmail.com" }